/**
 * Creates a CSRF token for demonstration purposes.
 * In a production environment, this token should be generated by the server
 * and sent to the client in a secure manner, typically set in a HTTP-only cookie
 * or included in the response body of a secured endpoint.
 * 
 * @returns A string representing a mock CSRF token.
 */
export const createCsrfToken = (): string => {
    // In a real scenario, this token should be received from the server.
    return 'emulation-token-CSRF';
};

/**
 * Verifies the provided CSRF token against an expected value.
 * In a real-world application, this function would compare the token submitted
 * by the client with the one stored in the user's session or a similar secure storage
 * to validate the authenticity of the request.
 * 
 * @param token - The CSRF token submitted by the client to be verified.
 * @returns A boolean value indicating whether the token is valid.
 */
export const verifyCsrfToken = (token: string): boolean => {
    // Check the sent token with the expected token
    return token === 'emulation-token-CSRF';
};
